# Introducción a numpy

In [5]:
import numpy as np

In [6]:
# Array cuyos valores son todo ceros
a = np.zeros((3,5)) 
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


DESCRIBE EL ARRAY

In [7]:
# Array cuyos valores son todo ceros
a = np.zeros((2,3,5)) 
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [8]:
print(a.ndim)
print(a.shape)
print(a.size)

3
(2, 3, 5)
30
